
FROM ubuntu:20.04 as radotp

LABEL maintainer="Abbas Gheydi <abbas.gheydi@gmail.com>"

RUN apt update && apt install -y openssl curl net-tools

RUN mkdir -p /etc/radotp

COPY radiusd.conf /etc/radotp

ADD ./deploy/radotp /bin/radotp

ENTRYPOINT [ "/bin/radotp" ]

EXPOSE 8080 8081
